---
title: "REPRORODUCIBLE RESEARCH WITH BITCOIN FORECASTING"
author: "AYOUB"
date: "`r Sys.Date()`"
output: pdf_document
---

## BITCOIN TIME SERIES


Bitcoin is the longest running and most well known cryptocurrency, first released as open source in 2009 by the anonymous Satoshi Nakamoto. Bitcoin serves as a decentralized medium of digital exchange, with transactions verified and recorded in a public distributed ledger (the blockchain) without the need for a trusted record keeping authority or central intermediary. Transaction blocks contain a SHA-256 cryptographic hash of previous transaction blocks, and are thus "chained" together, serving as an immutable record of all transactions that have ever occurred. As with any currency/commodity on the market, bitcoin trading and financial instruments soon followed public adoption of bitcoin and continue to grow.

*I will also diivide my document into two parts*

-   Data exploration. -Time series analysis.

*Taking my time series further i will use*

-ARIMA -SARIMA -PROPHET -To further the study my data is upto date to 2023 august.

*THE NEWLY ADDED MODELS* From my analysis am trying to improve the auhors work by adding the following two new models. 1. SARIMA 2. WAVENET MODEL
